version: '3.9'

services:
    minio:
        restart: always
        image: minio/minio:RELEASE.2022-07-04T21-02-54Z
        container_name: minio
        ports:
            - "9000:9000"
            - "9001:9001"
        command: server /data --console-address ':9001' --address ':9000'
        environment:
            - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
            - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
        volumes:
            - minio_data:/data

    mc:
        image: minio/mc:RELEASE.2022-06-26T18-51-48Z
        depends_on:
            - minio
        container_name: mc
        env_file:
            - .env
        entrypoint: >
            /bin/sh -c "
            /tmp/wait-for-it.sh minio:9000;
            /usr/bin/mc alias set minio http://minio:9000 ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY};
            /usr/bin/mc mb minio/mlflow;
            /usr/bin/mc mb minio/feast;
            /usr/bin/mc cp sample_products.parquet minio/feast;
            /usr/bin/mc cp test_products.parquet minio/feast;
            exit 0;
            "
        volumes:
            - ./wait-for-it.sh:/tmp/wait-for-it.sh
            - ./data/sample_products.parquet:/sample_products.parquet
            - ./data/test_products.parquet:/test_products.parquet

    mlflow_db:
        restart: always
        image: mysql:8.0.29
        container_name: mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql

    mlflow:
        restart: always
        build: ./mlflow
        image: mlflow_server
        container_name: mlflow_server
        depends_on:
         - minio
         - mlflow_db
        ports:
            - "5000:5000"
        environment:
            - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        command: mlflow server --backend-store-uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mlflow_db:3306/${MYSQL_DATABASE} --default-artifact-root s3://mlflow/ --host 0.0.0.0


    redis:
        restart: always
        image: redis:7
        container_name: redis
        ports:
            - "6379:6379"
   
    feast_ui:
        restart: always
        build: ./feast
        image: feast_ui
        container_name: feast_ui
        depends_on:
         - minio
         - redis
        environment:
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - FEAST_S3_ENDPOINT_URL=http://minio:9000
        ports:
            - "3378:3378"
#            - "6566:6566"
        volumes:
            - ./feast/feature_repo:/feature_repo


volumes:
    dbdata:
    minio_data:

networks:
  default:
    name: mlops
    external: true
